#
# Copyright 2019 StreamUnlimited
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += anti_rollback_common.o
obj-y += spl_anti_rollback.o
obj-y += ddr3l_1x4Gb_timing.o ddr3l_2x2Gb_timing.o ddr4_1x4Gb_timing.o ddr4_1x8Gb_timing.o
else
obj-y += stream195x.o
endif
